version: '3'

services:
  experiment-hub-backend:
    container_name: experiment-hub-backend
    image: carobaldino/experiment-hub-backend:v0.1
    ports:
      - 3000:3000
    command: npm run start:dev
