name: Deploy to DigitalOcean

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DigitalOcean Container Registry
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        uses: docker/login-action@v2.2.0
        with:
          # Server address of Docker registry. If not set then will default to Docker Hub
          registry: registry.digitalocean.com/experiment-hub-cr
          # Username used to log against the Docker registry
          username: ${{ secrets.DOCKER_USERNAME }}
          # Password or personal access token used to log against the Docker registry
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t registry.digitalocean.com/experiment-hub-cr/experiment-hub-backend:latest .
          docker push registry.digitalocean.com/experiment-hub-cr/experiment-hub-backend
